version: "3.5"

services:
  whisper_api:
    build:
      context: ./api
    container_name: "whisper_api"
    environment:
      OPENAI_API_KEY: "YOUR-OPEANAI-API-KEY"
    networks:
      whatsapp_network:
        ipv4_address: 172.25.0.2

  node:
    build: ./node
    container_name: node
    volumes:
       - ./node/data:/app/data/
    depends_on:
      - whisper_api
    environment:
      API_ADDRESS: whisper_api
      CHROME_DATA_PATH: "/app/data/"
    networks:
      whatsapp_network:
        ipv4_address: 172.25.0.3

networks:
  whatsapp_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
