version: "3"

services:
  whisper_api:
    build: ./api/
    container_name: "wspr_api"
    volumes:
      - ./api/.cache:/usr/src/app/.cache
    networks:
      mynetwork:
        ipv4_address: 172.25.0.2

  node:
    build: ./node
    container_name: node
    volumes:
      - .:/app/
    networks:
      mynetwork:
        ipv4_address: 172.25.0.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
