version: "3.5"

x-shared-variables: &shared-variables
  MODEL_VERSION: "tiny"

services:
  whisper_api:
    build:
      context: ./api
      args: *shared-variables
    container_name: "whisper_api"
    # volumes:
    #   - ./api/.cache:/usr/src/app/.cache
    environment: *shared-variables
    networks:
      mynetwork:
        ipv4_address: 172.25.0.2

  node:
    build: ./node
    container_name: node
    volumes:
       - ./node/data:/app/data/
    depends_on:
      - whisper_api
    environment:
      API_ADDRESS: whisper_api
      CHROME_DATA_PATH: "/app/data/"
    networks:
      mynetwork:
        ipv4_address: 172.25.0.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
